### ISSUE TITLE
Probleme de chemin

### ISSUE THREAD

**Issue by dav76df** [gabrielgrenier/ProjectLoopV2#14]
Bonjour,
J'ai essayé d'installer votre projet sur l'hebergeur 'fr.000webhost.com' mais j'ai un problème avec les chemins d'accès aux fichiers
Pourriez vous me venir en aide ?
Merci d'avance

ci joint le message

Warning: include_once(./classes/Database.php): failed to open stream: No such file or directory in /storage/ssd2/155/6087155/public_html/modele/TacheDAO.php on line 5

Warning: include_once(): Failed opening './classes/Database.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/155/6087155/public_html/modele/TacheDAO.php on line 5

Warning: include_once(./classes/Taches.php): failed to open stream: No such file or directory in /storage/ssd2/155/6087155/public_html/modele/TacheDAO.php on line 6

Warning: include_once(): Failed opening './classes/Taches.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/155/6087155/public_html/modele/TacheDAO.php on line 6

Warning: include_once(./classes/Database.php): failed to open stream: No such file or directory in /storage/ssd2/155/6087155/public_html/modele/ProjetDAO.php on line 5

Warning: include_once(): Failed opening './classes/Database.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/155/6087155/public_html/modele/ProjetDAO.php on line 5

Warning: include_once(./classes/Projets.php): failed to open stream: No such file or directory in /storage/ssd2/155/6087155/public_html/modele/ProjetDAO.php on line 6

Warning: include_once(): Failed opening './classes/Projets.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/155/6087155/public_html/modele/ProjetDAO.php on line 6

Warning: include_once(./classes/Database.php): failed to open stream: No such file or directory in /storage/ssd2/155/6087155/public_html/modele/UserDAO.php on line 3

Warning: include_once(): Failed opening './classes/Database.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/155/6087155/public_html/modele/UserDAO.php on line 3

Warning: include_once(./classes/User.php): failed to open stream: No such file or directory in /storage/ssd2/155/6087155/public_html/modele/UserDAO.php on line 4

Warning: include_once(): Failed opening './classes/User.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/155/6087155/public_html/modele/UserDAO.php on line 4

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /storage/ssd2/155/6087155/public_html/modele/TacheDAO.php:5) in /storage/ssd2/155/6087155/public_html/index.php on line 14

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /storage/ssd2/155/6087155/public_html/modele/TacheDAO.php:5) in /storage/ssd2/155/6087155/public_html/index.php on line 14

Warning: require_once(./controleur/DefaultAction.php): failed to open stream: No such file or directory in /storage/ssd2/155/6087155/public_html/controleur/ActionBuilder.php on line 2

Fatal error: require_once(): Failed opening required './controleur/DefaultAction.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/155/6087155/public_html/controleur/ActionBuilder.php on line 2

**Comment by gabrielgrenier** [comment]
Bonjour, désolé de ne pas t'avoir répondu je n'ai pas utiliser GitHub depuis 3 mois. Pour faire marcher le site tu dois utiliser UWamp ou un autre serveur local. Je vas attacher la base de données a ce message, il se peut qu'il ait plusieurs bug, l'application a été fait dans le cadre de mon cours d'hypermedia.
Bonne journée.
[BD.zip](https://github.com/gabrielgrenier/ProjectLoopV2/files/2357185/BD.zip)
